version: '3'

services:
  app:
    container_name: App
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:80
    volumes:
      - ./:/var/www/html

    depends_on:
      - db

  db:
    container_name: MariaDB
    image: mariadb:latest
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    restart: always